### ISSUE TITLE
Демка не пашет

### ISSUE THREAD

**Issue by Radzhab** [yandex/speechkitcloud#1]
В общем хочу заюзать web версию сиго чуда. Сперва в хроме пытался запустить, безрезультатно. Потом в IE. Он сказал что типа не поддерживает WebRTC, юзай Firefox. В файерфоксе он просит мне доступ к микрофону- я даю ему. Но безрезультатно. Пакеты не идут. Пробовал в яндекс.браузере-аналогично. 

вот скрин настроек. http://joxi.ru/dp278RbkHl3MA7
также залил jquery либы непосредственно в папку http://joxi.ru/XEA4NKXMHJDGmb

**Comment by mnvx** [comment]
Тоже была проблема с качеством распознавания. Попробовал другие модели (опция `--model`) - качество распознавания улучшилось радикально. 

```bash
asrclient-cli.py --model=queries --key=... ~/tmp/audio/textok.wav
```
