### ISSUE TITLE
asrclient-cli.py - Не передается значение аргумента --chunk-size при записи с аудио входа - Решение

### ISSUE THREAD

**Issue by hoverjet** [yandex/speechkitcloud#10]
Здравствуйте! 
Какое-то время я не мог разобрать, почему по сравнению с демо https://webasr.yandex.net/demo.html, распознавание при записи с аудио входа происходило очень долго. Фраза "привет" или "как дела" - до 10-15 секунд. В техподдержке, к сожалению, вразумительного ответа так и не дождался.
Оказалось, в скрипте зарылся небольшо баг (или фича?). Чтобы распознавание происходило быстрее, я уменьшил размер чанков до 1024:
python asrclient-cli.py --key=my_key --record --silent --chunk-size 1024
И чтобы скрипт понимал параметр chunk-size при записи с аудиовхода, изменил строчки
в asrclient-cli.py
chunks = client.read_chunks_from_pyaudio() на chunks = client.read_chunks_from_pyaudio(chunk_size)
в client.py
def read_chunks_from_pyaudio(): на def read_chunks_from_pyaudio(chunk_size):
yield stream.read(DEFAULT_CHUNK_SIZE_VALUE) на yield stream.read(chunk_size)

**Comment by bobuk** [comment]
Привет. А сможешь оформить нормальный pull-request?

**Comment by hoverjet** [comment]
Ок, вечером сделаю.

**Comment by hoverjet** [comment]
Сделал pull-request.

**Comment by bobuk** [comment]
СПАСИБО! :+1:

**Comment by Yagbul** [comment]
у кого такая ошибка выскакивала?

asrclient-cli.py --key=тут ключ /tmp/1495486034.87-pcm.wav
Traceback (most recent call last):
  File "/usr/local/bin/asrclient-cli.py", line 11, in <module>
    from asrclient import client
  File "/usr/local/lib/python3.4/site-packages/asrclient/client.py", line 14, in <module>
    from .basic_pb2 import ConnectionResponse
ImportError: No module named 'asrclient.basic_pb2'

**Comment by simakazi** [comment]
А proto-файлы скомпилировались?
Файл /usr/local/lib/python3.4/site-packages/asrclient/basic_pb2.py вообще существует?

**Comment by Yagbul** [comment]
Да, скомпилировались.
[root@localhost asrclient]# cd /usr/local/lib/python3.4/site-packages/asrclient
[root@localhost asrclient]# ls
basic.proto  __init__.py  transport.py      ttsclient.py  voiceproxy.proto
client.py    __pycache__  ttsbackend.proto  tts.proto


Сейчас опер система CentOS 6.9
По умолчанию стоит для операционки Python 2.6.6
Я еще дополнительно поставил Python 3.4
Похоже с этим связано, хотя в каталоге /usr/local/bin/ находится файл asrclient-cli.py и строка начинается с #!/usr/local/bin/python3.4
А в файле client.py (/usr/local/lib/python3.4/site-packages/asrclient) начинается на #!/usr/bin/env python

В линуксе слабо разбираюсь...

**Comment by simakazi** [comment]
Не скомпилировались, файлы *_pb2.py отсутствуют.
Как и написано в документации, надо сделать следующее:
protoc -I=asrclient --python_out=asrclient asrclient/*.proto
В итоге появятся файлы *_pb2.py.
В CentOS protoc предоставляется пакетом protobuf-compiler.

**Comment by Yagbul** [comment]
Все проделал, да, по описанию здесь, нужно было добавить protoc -I=asrclient --python_out=asrclient asrclient/.proto

Но другая проблема возникла с utf-8

Похоже  яндекс скрипт написали под питон версии 2: начинаю догадываться

[root@localhost tmp]# asrclient-cli.py 1495483797.52-pcm.wav                    
Traceback (most recent call last):
  File "/usr/local/bin/asrclient-cli.py", line 11, in <module>
    from asrclient import client
  File "/usr/local/lib/python3.4/site-packages/asrclient/client.py", line 14, in <module>
    from .basic_pb2 import ConnectionResponse
  File "/usr/local/lib/python3.4/site-packages/asrclient/basic_pb2.py", line 84, in <module>
    has_default_value=False, default_value=unicode("", "utf-8"),
NameError: name 'unicode' is not defined

**Comment by simakazi** [comment]
Это не яндекс скрипт, это под CentOS старый protoc, который компилирует python2-only обвязку. Рекомендую или обновить protoc, или использовать python2.

**Comment by Yagbul** [comment]
Заработало! После установки python 2 версии

[root@localhost tmp]# asrclient-cli.py /tmp/1495548285.134-pcm.wav
INFO:asrclient:uuid=8081fd4b33______________b98b712e9b2
INFO:asrclient:Connected to asr.yandex.net:80.
INFO:asrclient:session_id=20828230______________________e-5ad957b9356d
INFO:asrclient:Recognition was started.
INFO:asrclient:About to send chunk 0 (65536 bytes)
INFO:asrclient:entering send() :start index 0, pending answers 0, chunks answered 0
INFO:asrclient:About to send chunk 1 (65536 bytes)
INFO:asrclient:entering send() :start index 0, pending answers 1, chunks answered 0
INFO:asrclient:About to send chunk 2 (65536 bytes)
INFO:asrclient:entering send() :start index 0, pending answers 2, chunks answered 0
INFO:asrclient:About to send chunk 3 (29996 bytes)
INFO:asrclient:entering send() :start index 0, pending answers 3, chunks answered 0
INFO:asrclient:No more chunks. Finalizing recognition.
INFO:asrclient:entering send() :start index 0, pending answers 4, chunks answered 0
INFO:asrclient:got response: endOfUtt=False; len(recognition)=1; messages_count=2
INFO:asrclient:got response: endOfUtt=False; len(recognition)=1; messages_count=2
INFO:asrclient:got response: endOfUtt=True; len(recognition)=5; messages_count=1
INFO:asrclient:Chunks from 0 to 5.
1 2 3 1 2 3 город казань город казань казань.
from 0.0 to 2.34999990463
INFO:asrclient:Recognition is done.
INFO:asrclient:Start at [24.05.2017 15:32:56], finish at [24.05.2017 15:32:59], took 3.37375116348 seconds
INFO:asrclient:Avg. 1.18562389642 chunks per second

**Comment by Yagbul** [comment]
simakazi, спасибо большое.
Другой вопрос теперь, как выделить распознанный текст "1 2 3 1 2 3 город казань город казань казань."   и передать его в другую среду? :)
