### ISSUE TITLE
Как остановить озвучивание текста в webspeechkit?

### ISSUE THREAD

**Issue by pskucherov** [yandex/speechkitcloud#16]
Посмотрел https://github.com/yandex/speechkitcloud/blob/master/webspeechkit/src/tts.js, но не нашёл там API для управления.

Как остановить озвучивание текста? 

Возможно ли продолжить воспроизведение с того момента, на котором пользователь остановил?

**Comment by simakazi** [comment]
День добрый.
Вы можете воспользоваться функцией `speak` объекта `ya.speechkit.Tts`, передав в неё в объекте опций среди прочего callback `dataCallback`.
В этот callback будет передан `Blob` с готовым звуком в формате wav.
Таким образом получается следующий код:
```
var tts = ya.speechkit.Tts({speaker: 'jane', emotion: 'good', apikey: '...'});
var audio;
tts.speak('1 2 3', {
    dataCallback: function (blob) {
       var url = URL.createObjectURL(blob);
       audio =  new Audio(url);
       audio.play();
    }
});
```
Здесь у объекта `audio` есть также метод `pause`.
Чтобы продолжить затем воспроизведение с места остановки, можно вызвать опять метод `play`.

**Comment by pskucherov** [comment]
точно, не догадался так сделать. спасибо.
