### ISSUE TITLE
number of hardware contexts reached maximum (6) in webkit

### ISSUE THREAD

**Issue by Sigak** [yandex/speechkitcloud#2]
When I start recording audio multiple times, my node-webkit app based on this example throws a "SyntaxError: Failed to construct 'AudioContext': number of hardware contexts reached maximum (6)".
I fixed it by assigning Recorder.context to a variable in order not to create an AudioContext twice.
I'm not sure how correct it is, so I would like you to look at this issue, please.

**Comment by simakazi** [comment]
Fixed in latest commit.
