### ISSUE TITLE
Available speakers

### ISSUE THREAD

**Issue by tofutim** [yandex/speechkitcloud#6]
Hi, how does one retrieve the available speakers or languages for TTS? Is it on a website somewhere?

Also, for TTS, I see that there is /tts?, /generate? and /crafted? which you use here. What are the differences? Looks like /tts? does not require a key.

**Comment by simakazi** [comment]
Hello!
With new version of Yandex SpeechKit Web API you can use method ya.speechkit.Tts.speakers.
